name: safedrl
channels:
  - pytorch
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2019.5.15=0
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - mkl=2019.4=243
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - olefile=0.46=py36_0
  - openssl=1.1.1c=h7b6447c_1
  - pip=19.1.1=py36_0
  - pycparser=2.19=py36_0
  - python=3.6.9=h265db76_0
  - pytorch=1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.3.0=py36_cu10.0.130_1
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.7.1
    - apex==0.1
    - astor==0.8.0
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==1.5.0
    - click==7.0
    - cloudpickle==1.2.1
    - colorama==0.4.1
    - cycler==0.10.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - docopt==0.6.2
    - entrypoints==0.3
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.17.1
    - gast==0.2.2
    - grpcio==1.11.0
    - gym==0.14.0
    - html5lib==0.9999999
    - importlib-metadata==0.19
    - ipykernel==5.1.2
    - ipython==7.7.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.14.1
    - jinja2==2.10.1
    - jsonpickle==1.2
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.1
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mistune==0.8.4
    - more-itertools==7.2.0
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - notebook==6.0.0
    - numpy==1.14.5
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==5.4.1
    - pluggy==0.12.0
    - progressbar2==3.42.0
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - protobuf==3.9.1
    - ptyprocess==0.6.0
    - py==1.8.0
    - pyarrow==0.14.1
    - pyglet==1.3.2
    - pygments==2.4.2
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - pytest==3.10.1
    - python-dateutil==2.8.0
    - python-utils==2.3.0
    - pyyaml==5.1.2
    - pyzmq==18.0.2
    - qtconsole==4.5.2
    - ray==0.7.3
    - redis==3.3.6
    - scipy==1.3.0
    - send2trash==1.5.0
    - tensorboard==1.7.0
    - tensorboardx==1.8
    - tensorflow==1.7.1
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torchtest==0.5
    - tornado==6.0.3
    - traitlets==4.3.2
    - unityagents==0.4.0
    - wcwidth==0.1.7
    - werkzeug==0.15.5
    - widgetsnbextension==3.5.1
    - zipp==0.5.2
prefix: /home/edoardo/anaconda3/envs/safedrl

